// Question bank for the restructured quiz system.
//   - One 10-item "module quiz" per week (weeks 1-13), week_no = module week.
//   - One 40-item "monthly exam" per 4 modules (1-4, 5-8, 9-12); exam questions
//     are copies of the covered modules' questions, stored as standalone rows.
// Applied by apply-quizzes.mjs. Exported shape:
//   [{ kind, week_no, title, description, time_limit_sec, questions:
//      [{ q, o: [4 options], c: correctIndex }] }]

const q = (q, o, c) => ({ q, o, c });

export const curriculumQuizzes = [
  {
    kind: "module",
    week_no: 1,
    title: "Module 1 Quiz — Introduction to Cybersecurity",
    description: "10 questions that check your understanding of threats, attackers, and the CIA triad.",
    time_limit_sec: 600,
    questions: [
      q("The CIA triad stands for which three security goals?",
        ["Confidentiality, Integrity, Availability", "Computing, Identity, Access", "Control, Isolation, Authentication", "Cryptography, Integrity, Authorization"], 0),
      q("A nurse\u2019s shared account lets a stranger read a patient\u2019s chart. Which goal is broken?",
        ["Confidentiality", "Integrity", "Availability", "Authentication"], 0),
      q("An attacker silently changes a prescribed medication dose in the system. Which goal is broken?",
        ["Integrity", "Confidentiality", "Availability", "Non-repudiation"], 0),
      q("What is a man-in-the-middle attack?",
        ["An attacker secretly intercepts traffic between two parties", "Malware that encrypts files for ransom", "A flood of traffic to take a service down", "Guessing passwords until one works"], 0),
      q("What does a phishing email typically try to do?",
        ["Trick the victim into revealing credentials or installing malware", "Encrypt the victim's hard drive", "Scan the victim's network for open ports", "Crash the victim's computer hardware"], 0),
      q("Which actor is an insider threat?",
        ["An employee who abuses access they already have", "A stranger scanning public web servers", "A ransomware gang demanding payment", "A bug bounty researcher testing a public program"], 0),
      q("What is the main defensive quality of a honeypot?",
        ["It looks vulnerable so attackers waste effort on it instead of real systems", "It blocks all inbound traffic at the firewall", "It decrypts all encrypted traffic on the network", "It backs up user data automatically"], 0),
      q("Which attack type floods a service with traffic so legitimate users cannot reach it?",
        ["Denial of service", "Phishing", "SQL injection", "Session hijacking"], 0),
      q("A small business left its payment terminal directly reachable from the internet. What is the core mistake?",
        ["Not modeling the threats and exposing an unnecessary service", "Using a weak cipher for disk encryption", "Running outdated antivirus definitions", "Not hiring a large security team"], 0),
      q("Cybersecurity blends which three things?",
        ["Technology, process, and people", "Hardware, software, and marketing", "Finance, legal, and sales", "Networks, cables, and printers"], 0),
    ],
  },
  {
    kind: "module",
    week_no: 2,
    title: "Module 2 Quiz — Networking Fundamentals",
    description: "10 questions on network devices, protocols, addressing, and resolution services.",
    time_limit_sec: 600,
    questions: [
      q("Which device connects multiple devices inside one local network (LAN)?",
        ["Switch", "Router", "Modem", "Firewall"], 0),
      q("Which device connects different networks together?",
        ["Router", "Hub", "Repeater", "Load balancer"], 0),
      q("The internet is mostly made up of:",
        ["Routers connected to each other across long distances", "One giant central switch", "Satellites only", "Private home networks only"], 0),
      q("Which protocol guarantees reliable, ordered delivery of data?",
        ["TCP", "UDP", "ICMP", "ARP"], 0),
      q("What does DNS do?",
        ["Resolves human-friendly domain names into IP addresses", "Assigns IP addresses dynamically", "Encrypts web traffic", "Blocks unwanted traffic"], 0),
      q("What does DHCP provide?",
        ["Automatic IP address assignment to clients", "Domain name translation", "Firewall rules", "Virus signatures"], 0),
      q("Which port number is normally associated with HTTPS?",
        ["443", "80", "21", "53"], 0),
      q("What does the ping utility use to test reachability?",
        ["ICMP", "UDP", "SMTP", "ARP"], 0),
      q("What is the main purpose of a subnet mask?",
        ["Show which part of an IP address identifies the local network", "Hide the public IP from the internet", "Encrypt packets in transit", "Convert domain names to addresses"], 0),
      q("A port scan that identifies running services on a host is the first task of:",
        ["Reconnaissance", "Eradication", "Reporting", "Cleanup"], 0),
    ],
  },
  {
    kind: "module",
    week_no: 3,
    title: "Module 3 Quiz — Linux & OS Essentials",
    description: "10 questions on Linux filesystems, commands, permissions, and package management.",
    time_limit_sec: 600,
    questions: [
      q("Which command lists the contents of a directory?",
        ["ls", "cd", "cat", "rm"], 0),
      q("What does sudo allow you to do?",
        ["Run a command as the root (administrator) user", "List open sockets", "Change the hostname", "Manage firewall chains"], 0),
      q("Which directory stores system configuration files?",
        ["/etc", "/bin", "/tmp", "/mnt"], 0),
      q("The command cat is used to:",
        ["Print a file's contents to the terminal", "Remove a file", "Copy files between directories", "Change file permissions"], 0),
      q("What does chmod change?",
        ["File and directory permissions", "The current timezone", "Disk partition layout", "Kernel version"], 0),
      q("On Debian-based systems, which tool installs and updates packages?",
        ["apt", "npm", "pip", "gem"], 0),
      q("The phrase \u201ceverything is a file\u201d means Linux represents:", 
        ["Devices, commands, and configs as files", "Only documents as files", "Only disk data as files", "Nothing, it is a myth"], 0),
      q("Which command searches for text patterns inside files?",
        ["grep", "ls", "pwd", "touch"], 0),
      q("A .deb package is used on:",
        ["Debian-based Linux distributions", "Windows", "macOS", "Android boot images"], 0),
      q("The root of the filesystem on Linux is referred to as:",
        ["/", "~", "C:", "%APPDATA%"], 0),
    ],
  },
  {
    kind: "module",
    week_no: 4,
    title: "Module 4 Quiz — Cryptography Basics",
    description: "10 questions on encryption, hashing, key exchange, and integrity.",
    time_limit_sec: 600,
    questions: [
      q("Encryption turns plaintext into:",
        ["Ciphertext", "A hash", "A digital signature", "A MAC address"], 0),
      q("Symmetric encryption uses:",
        ["The same key to encrypt and decrypt", "Two different keys", "No keys at all", "Only rotation ciphers"], 0),
      q("In public-key (asymmetric) cryptography, the public key is used to:",
        ["Encrypt messages that only the private key can decrypt", "Decrypt messages sent to anyone", "Generate passwords", "Bypass firewalls"], 0),
      q("Hashes are mainly used to verify:",
        ["Data integrity", "Network speed", "Server uptime", "File size on disk"], 0),
      q("Adding a salt to a password hash protects against:",
        ["Precomputed rainbow tables", "Buffer overflows", "Phishing emails", "DDoS attacks"], 0),
      q("AES is classified as:",
        ["A symmetric block cipher", "An asymmetric cipher", "A hashing only tool", "A protocol for email"], 0),
      q("Diffie-Hellman key exchange lets two parties:",
        ["Agree on a shared secret without transmitting it in the clear", "Encrypt files with one key", "Sign documents publicly", "Compress large files"], 0),
      q("A digital signature provides:",
        ["Authenticity and integrity", "Faster downloads", "Smaller file sizes", "Anonymous browsing"], 0),
      q("Steganography is the practice of:",
        ["Hiding a message inside other media such as an image", "Encrypting a message with a long key", "Cracking passwords with hashcat", "Blocking brute-force attempts"], 0),
      q("Brute-forcing a 128-bit AES key is:",
        ["Impractical with today's computing power", "Fast with a normal laptop", "Guaranteed in seconds", "Only possible offline"], 0),
    ],
  },
  {
    kind: "module",
    week_no: 5,
    title: "Module 5 Quiz — Web Security Essentials",
    description: "10 questions on web attacks: injections, XSS, phishing, and session security.",
    time_limit_sec: 600,
    questions: [
      q("Cross-site scripting (XSS) injects which kind of code into pages?",
        ["Client-side scripts (JavaScript)", "Server-side PHP", "Device drivers", "Kernel modules"], 0),
      q("SQL injection lets an attacker:",
        ["Manipulate database queries to read or alter data", "Forget the server's hostname", "Overclock the CPU", "Change the Wi-Fi password"], 0),
      q("The best defense against SQL injection is:",
        ["Parameterized (prepared) queries", "Longer passwords", "Using only GET requests", "Disabling HTTPS"], 0),
      q("What does HTTPS protect against?",
        ["Eavesdropping on data in transit", "Local disk corruption", "Physical theft of the laptop", "Weak passwords"], 0),
      q("Session hijacking usually involves stealing:",
        ["Cookies or session tokens", "The page background color", "The browser name", "The network cable"], 0),
      q("Clickjacking tricks a user into:",
        ["Clicking invisible UI elements that perform unwanted actions", "Installing Linux for free", "Updating the browser firmware", "Running speed tests"], 0),
      q("Remote Code Execution (RCE) means an attacker can:",
        ["Run commands on the targeted server", "Only read the homepage", "Change the DNS root servers", "Block all email"], 0),
      q("Directory traversal tries to:",
        ["Read files outside the web root", "Encrypt all uploads", "Add more users", "Speed up the site"], 0),
      q("A phishing attack targeting one specific high-value individual is called:",
        ["Spear phishing", "Banner grabbing", "Port knocking", "Responsible disclosure"], 0),
      q("The strongest single habit that prevents many web account takeovers is:",
        ["Enabling multi-factor authentication", "Changing the browser theme", "Clearing cache weekly", "Using incognito windows"], 0),
    ],
  },
  {
    kind: "module",
    week_no: 6,
    title: "Module 6 Quiz — Network Security, Firewalls & Monitoring",
    description: "10 questions on firewalls, port security, monitoring, and network defense.",
    time_limit_sec: 600,
    questions: [
      q("A firewall's primary job is to:",
        ["Filter and control allowed traffic in and out", "Encrypt all application data", "Back up user files", "Assign IP addresses"], 0),
      q("A stateful firewall tracks:",
        ["The state of active connections", "Website bookmarks", "Printer queues", "Battery health"], 0),
      q("pfSense is best described as:",
        ["Open-source firewall/router software", "A commercial antivirus", "A web browser", "A password manager"], 0),
      q("Port security on a managed switch controls:",
        ["Which devices/MAC addresses may connect to a port", "Which apps may run", "Which WiFi channel is used", "How fast the fan spins"], 0),
      q("An Intrusion Detection System (IDS) primarily:",
        ["Detects suspicious activity and alerts analysts", "Blocks all traffic by default", "Encrypts the hard drive", "Assigns DHCP leases"], 0),
      q("A DMZ is:",
        ["A semi-trusted zone hosting public services", "A fully trusted internal LAN", "A type of malware", "A backup strategy"], 0),
      q("A VPN provides:",
        ["An encrypted tunnel between endpoints", "A list of open ports", "Faster CPU performance", "A second operating system"], 0),
      q("A SIEM is used to:",
        ["Collect and correlate logs and alerts", "Burn DVDs", "Format hard drives", "Design logos"], 0),
      q("The \u201cdefault deny\u201d firewall philosophy means:",
        ["Allow only what is explicitly needed", "Block everything including vitals", "Deny logins after dusk", "Allow everything then log"], 0),
      q("Wireshark is a tool for:",
        ["Analyzing network packets", "Writing firewall reports", "Managing users", "Scanning for malware on disks"], 0),
    ],
  },
  {
    kind: "module",
    week_no: 7,
    title: "Module 7 Quiz — Incident Response & Forensics",
    description: "10 questions on IR phases, containment, evidence handling, and forensic tools.",
    time_limit_sec: 600,
    questions: [
      q("The goal of incident containment is to:",
        ["Stop the attack from spreading further", "Delete all logs", "Rebuild the network", "Ignore the alert"], 0),
      q("A forensic image of a drive should be:",
        ["A bit-for-bit copy to preserve evidence", "A compressed summary", "Just the deleted files", "An antivirus scan report"], 0),
      q("A write blocker is used to:",
        ["Prevent any modification of evidence media", "Block malicious websites", "Stop email spam", "Disable USB keyboards"], 0),
      q("Hashing collected evidence verifies:",
        ["Evidence integrity over time", "Network speed", "Evidence size", "File timestamps"], 0),
      q("Forensic timelines (like with Plaso) help investigators:",
        ["Reconstruct the order of events", "Recover passwords instantly", "Predict future attacks", "Generate reports automatically"], 0),
      q("Memory (RAM) forensics is valuable because it reveals:",
        ["Running processes and volatile artifacts", "Files deleted years ago", "The CPU temperature history", "Email server quotas"], 0),
      q("An IR playbook is:",
        ["Predefined response steps for a type of incident", "A book of employee credentials", "A firewall rule set", "A backup schedule"], 0),
      q("Chain of custody records:",
        ["Who handled the evidence and when", "Routed packets", "Which service accounts exist", "The weather during the incident"], 0),
      q("During triage, an analyst first needs to:",
        ["Validate and prioritize the alert", "Format the disk", "Publish a press release", "Shut down the firewall"], 0),
      q("Which phase comes after identification in a typical IR lifecycle?",
        ["Containment", "Recovery", "Preparation", "Sales"], 0),
    ],
  },
  {
    kind: "module",
    week_no: 8,
    title: "Module 8 Quiz — Ethical Hacking, CTF & Roadmap",
    description: "10 questions on legal offensive testing, CTF practice, and disclosure.",
    time_limit_sec: 600,
    questions: [
      q("The absolute rule of offensive security is:",
        ["Only attack what you are authorized to attack", "Always attack the newest targets", "Never report findings", "Share exploits publicly first"], 0),
      q("In a penetration test, the scope is defined by:",
        ["The rules of engagement document", "The tester's curiosity", "Internet rumors", "The number of subdomains"], 0),
      q("nmap is primarily used for:",
        ["Host discovery and port/service scanning", "Cracking passwords", "Building web forms", "Analyzing memory dumps"], 0),
      q("In a CTF, a \u201cflag\u201d is:",
        ["The proof string that solves a challenge", "A password manager feature", "A network traceroute", "A type of certificate"], 0),
      q("TryHackMe and HackTheBox provide:",
        ["Legal, practice environments for offensive skills", "Web hosting for phishing sites", "A dark web marketplace", "Corporate spam lists"], 0),
      q("If you find a flaw in a program you do not own, responsible disclosure means:",
        ["Report privately and give the owner time to fix", "Post it immediately on social media", "Exploit it for profit", "Sell it to the highest bidder"], 0),
      q("The rules of engagement does NOT include:",
        ["The tester's preferred coffee brand", "Allowed targets and techniques", "Time window of testing", "Emergency-stop contact"], 0),
      q("Which of these is a legal reason to study hashing tools?",
        ["Analyzing passwords you own or in labs", "Attacking someone else's service", "Gaining unauthorized access", "Bypassing school exams"], 0),
      q("A pentest report should emphasize:",
        ["Findings ordered by risk with fixes", "Only the tools used", "The tester's credentials count", "Server purchase receipts"], 0),
      q("The typical first certification recommended for a cybersecurity beginner is:",
        ["CompTIA Security+", "CISSP", "OSCP", "CISM"], 0),
    ],
  },
  {
    kind: "module",
    week_no: 9,
    title: "Module 9 Quiz — Cybersecurity Roles & Career Paths",
    description: "10 questions on the roles, specializations, and career ladders in the field.",
    time_limit_sec: 600,
    questions: [
      q("A SOC analyst belongs to which team?",
        ["Blue team (defensive)", "Red team (offensive)", "Purple team (hybrid)", "No team"], 0),
      q("A penetration tester belongs to which family?",
        ["Offensive (red team)", "Defensive (blue team)", "GRC", "Sales"], 0),
      q("Which of these is a GRC analyst's main job?",
        ["Policies, risk register, and compliance evidence", "Scanning networks for open ports", "Writing exploit chains", "Installing firewalls"], 0),
      q("The usual entry point for a defensive career is:",
        ["SOC Tier 1 analyst", "CISO", "Security architect", "Bug bounty lead"], 0),
      q("Certifications like CySA+ and PenTest+ are:",
        ["Specialty certs beyond the entry Security+ level", "Hardware certifications", "Typing tests", "Language exams"], 0),
      q("Which role designs security at the enterprise level and owns risk strategy?",
        ["Security architect / CISO", "Help desk technician", "Data entry clerk", "Network cable engineer"], 0),
      q("Employers weigh hands-on proof such as TryHackMe labs and home projects:",
        ["As strong evidence alongside certifications", "As irrelevant", "As proof of illegal activity", "Only for managers"], 0),
      q("The technical foundation shared by nearly every role includes:",
        ["Networking and Linux", "Guitar and painting", "Marketing and sales", "Cooking and driving"], 0),
      q("An incident responder's job during a real attack is to:",
        ["Contain, eradicate, recover, and report", "Write marketing copy", "Host the company website", "Manage payroll"], 0),
      q("Which role works with identity, least privilege, and MFA lifecycles?",
        ["Identity and access (IAM) specialist", "Pentester", "CTF designer", "Logo designer"], 0),
    ],
  },
  {
    kind: "module",
    week_no: 10,
    title: "Module 10 Quiz — Blue Team Ops: Inside a SOC",
    description: "10 questions on SOC tiers, triage, indicators of compromise, and detection tooling.",
    time_limit_sec: 600,
    questions: [
      q("A Tier 1 SOC analyst mainly does:",
        ["Monitor dashboards and triage alerts", "Hunt for zero-day exploits", "Manage the company budget", "Design detection rules only"], 0),
      q("An alert that fires but is not a real threat is called a:",
        ["False positive", "True positive", "False negative", "Beacon"], 0),
      q("Which is a network-based indicator of compromise?",
        ["Connection to a known-bad IP", "A typo in an email", "A new desk chair", "A faster fan"], 0),
      q("A playbook is used in a SOC to:",
        ["Define the steps to respond to a type of alert", "List employee birthdays", "Track printer paper", "Choose site themes"], 0),
      q("When an alert is confirmed as a real incident, the analyst should:",
        ["Escalate to the next tier with evidence", "Delete the host", "Ignore it if busy", "Reimage the whole network"], 0),
      q("A SIEM performs which core function?",
        ["Centralizes logs and correlates alerts", "Stores backups in the cloud", "Offers chat rooms", "Encodes video"], 0),
      q("EDR stands for:",
        ["Endpoint Detection and Response", "External Data Router", "Encrypted Data Repository", "Event Driven Reporting"], 0),
      q("Beaconing in traffic often appears as:",
        ["Regular connections to one external host", "Random DNS typos", "Many local printer jobs", "Nothing suspicious"], 0),
      q("What is the first step of alert triage?",
        ["Acknowledge the alert", "Write a press release", "Format the disk", "Call the CISO"], 0),
      q("Threat hunting is:",
        ["Proactively searching for attacks that produced no alert", "Waiting for automated alerts only", "Scanning for WiFi passwords", "Reading news headlines"], 0),
    ],
  },
  {
    kind: "module",
    week_no: 11,
    title: "Module 11 Quiz — Pentesting & Responsible Offense",
    description: "10 questions on pentest methodology, scoping, reporting, and ethics.",
    time_limit_sec: 600,
    questions: [
      q("Before any authorized test begins, both sides must sign:",
        ["Rules of engagement", "A non-disclosure of intent", "A purchase order for tools", "A hotel reservation"], 0),
      q("Which phase comes first in a pentest lifecycle?",
        ["Reconnaissance", "Exploitation", "Post-exploitation", "Reporting"], 0),
      q("OSINT refers to:",
        ["Gathering information from open sources", "Offline system inspection", "Overclocked settings", "A type of firewall"], 0),
      q("During exploitation, the professional goal is to:",
        ["Prove impact with minimal access, not cause damage", "Delete critical data", "Install persistence quietly", "Notify the press"], 0),
      q("Findings in a pentest report should be sorted by:",
        ["Risk/severity", "Tester preference", "Speaking order", "Question number"], 0),
      q("A bug bounty program allows:",
        ["Testing only within the program's published scope and rules", "Testing any internet target", "Attacking bank accounts for fun", "Selling stolen data"], 0),
      q("Which is an appropriate target for password cracking practice?",
        ["Your own hashes or lab machines", "Your neighbor's WiFi", "A museum database", "Any public login page"], 0),
      q("A red team exercise differs from a typical pentest because it:",
        ["Simulates a real adversary, evading detection", "Only scans open ports", "Never writes a report", "Avoids exploiting systems"], 0),
      q("If you spot a severe issue during an authorized engagement, you should:",
        ["Follow the agreed emergency-stop procedure and notify the client", "Continue silently to win", "Publish it immediately", "Ignore it"], 0),
      q("Responsible disclosure gives the vendor:",
        ["Reasonable time to fix before publication", "No time at all", "A legal threat", "A free badge"], 0),
    ],
  },
  {
    kind: "module",
    week_no: 12,
    title: "Module 12 Quiz — Purple Team & DevSecOps",
    description: "10 questions on threat modeling, pipeline security, and engineering practices.",
    time_limit_sec: 600,
    questions: [
      q("A purple team practice means:",
        ["Red and blue teams work together toward shared learning", "Only red team works", "Only blue team exists", "Teams never talk"], 0),
      q("SAST scans to find vulnerabilities:",
        ["In source code during the build", "In the running application only", "In email headers", "In office furniture"], 0),
      q("DAST exercises:",
        ["The running application like an attacker", "Only the source code", "The network cables", "The power supply"], 0),
      q("The principle of \u201cshifting left\u201d means:",
        ["Finding bugs as early as possible in the pipeline", "Moving servers overseas", "Rotating jobs every month", "Removing tests"], 0),
      q("IaC scanning checks templates for:",
        ["Security misconfigurations before deployment", "Font compatibility", "Battery drain", "Employee names"], 0),
      q("Threat modeling asks, among others:",
        ["What can go wrong with what we are building?", "How many users visit?", "What color is the logo?", "When is the deadline?"], 0),
      q("In STRIDE, the D stands for:",
        ["Denial of service", "Data packets", "Digital keys", "Downloads"], 0),
      q("Zero trust architecture means:",
        ["Nothing is trusted just because it is inside the network", "Block everyone forever", "Never use passwords", "Trust everything by default"], 0),
      q("Secret scanning in CI/CD aims to catch:",
        ["API keys and passwords before they reach the repo", "Open source licenses", "Build times", "Video formats"], 0),
      q("Dependency scanning alerts when:",
        ["A shipped library has a known vulnerability", "The build takes too long", "A font is missing", "The dashboard is red"], 0),
    ],
  },
  {
    kind: "module",
    week_no: 13,
    title: "Module 13 Quiz — GRC, Audits & Cyber Leadership",
    description: "10 questions on governance, risk management, frameworks, and leadership.",
    time_limit_sec: 600,
    questions: [
      q("Governance in cybersecurity decides:",
        ["Who sets policy and is accountable", "Which firewall brand to buy", "The office furniture", "Server placement"], 0),
      q("A risk register tracks for each risk:",
        ["Likelihood, impact, and chosen treatment", "Only the cost", "The employee ID", "Nothing"], 0),
      q("Which is NOT a standard risk treatment?",
        ["Ignoring the asset completely", "Accept", "Transfer", "Mitigate"], 0),
      q("ISO/IEC 27001 is:",
        ["A certifiable information security management standard", "A virus report", "A network protocol", "A font family"], 0),
      q("The NIST CSF organizing functions are:",
        ["Identify, Protect, Detect, Respond, Recover", "Plan, Code, Test, Ship, Celebrate", "Scan, Crack, Fix, Sell, Repeat", "A, B, C, D, E"], 0),
      q("CIS Controls are best described as:",
        ["A prioritized list of actions that stop most attacks", "A new programming language", "A cloud pricing model", "A social media platform"], 0),
      q("SOC 2 is primarily:",
        ["A report clients expect from cloud service providers", "A personal firewall", "A marketing tool", "A type of certificate"], 0),
      q("An audit verifies that:",
        ["What an organization claims matches what it actually does", "The website looks nice", "The office is clean", "Employees use email"], 0),
      q("A GRC analyst's typical artifact is:",
        ["A maintained risk register and audit evidence", "A packet capture", "An exploit script", "A user manual"], 0),
      q("The CISO role is strongest when the holder can:",
        ["Translate risk into business language AND hold technical depth", "Only write policies", "Only run scans", "Avoid the board"], 0),
    ],
  },

  {
    kind: "exam",
    week_no: 14,
    title: "Monthly Exam 1 — Modules 1 to 4",
    description: "40 questions covering Modules 1 (intro), 2 (networking), 3 (Linux), and 4 (cryptography). 40 minutes.",
    time_limit_sec: 2400,
    fromWeeks: [1, 2, 3, 4],
  },
  {
    kind: "exam",
    week_no: 15,
    title: "Monthly Exam 2 — Modules 5 to 8",
    description: "40 questions covering Modules 5 (web), 6 (network security), 7 (IR/forensics), and 8 (ethical hacking). 40 minutes.",
    time_limit_sec: 2400,
    fromWeeks: [5, 6, 7, 8],
  },
  {
    kind: "exam",
    week_no: 16,
    title: "Monthly Exam 3 — Modules 9 to 12",
    description: "40 questions covering Modules 9 (roles), 10 (SOC), 11 (pentesting), and 12 (DevSecOps). 40 minutes.",
    time_limit_sec: 2400,
    fromWeeks: [9, 10, 11, 12],
  },
];